const BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'https://localhost:8443';

export const ENDPOINTS = {
  metroLines: `${BASE_URL}/metro-lines`,
  stations: `${BASE_URL}/stations`,
  tickets: `${BASE_URL}/tickets`,
  ticketTypes: `${BASE_URL}/tickets/types`,
  ticketStatistics: `${BASE_URL}/tickets/statistics`,
  ticketById: (id: string|number) => `${BASE_URL}/tickets/${id}`,
  ticketPassenger: (passengerId: string|number) => `${BASE_URL}/tickets/passenger/${passengerId}`,
  ticketPassengerByNationalId: (nationalId: string) => `${BASE_URL}/tickets/passenger/by-national-id/${nationalId}`,
  ticketPassengerHistory: (passengerId: string|number) => `${BASE_URL}/tickets/passenger-history/${passengerId}`,
  ticketByNumber: (ticketNumber: string) => `${BASE_URL}/tickets/number/${ticketNumber}`,
  ticketNationalIdHistory: (nationalId: string) => `${BASE_URL}/tickets/national-id-history/${nationalId}`,
  ticketPurchase: `${BASE_URL}/tickets/purchase`,
  login: `${BASE_URL}/api/auth/login`,
  // Ticket Cart endpoints
  ticketCart: (staffId: string|number) => `${BASE_URL}/v1/ticket-cart/${staffId}`,
  ticketCartItem: (staffId: string|number, itemId: string|number) => `${BASE_URL}/v1/ticket-cart/${staffId}/items/${itemId}`,
  ticketCartClear: (staffId: string|number) => `${BASE_URL}/v1/ticket-cart/${staffId}`,
  ticketCartPassenger: (staffId: string|number) => `${BASE_URL}/v1/ticket-cart/${staffId}/passenger`,
  ticketCartItemQuantity: (staffId: string|number, itemId: string|number) => `${BASE_URL}/v1/ticket-cart/${staffId}/items/${itemId}`,
  ticketCartAddItem: (staffId: string|number) => `${BASE_URL}/v1/ticket-cart/${staffId}/items`,
  ticketCartCheckout: (staffId: string|number) => `${BASE_URL}/v1/ticket-cart/${staffId}/checkout`,
  // Staff Management endpoints
  staffProfile: `${BASE_URL}/api/staff/profile`,
  staffById: (id: string|number) => `${BASE_URL}/api/staff/${id}`,
  staffPerformance: (id: string|number) => `${BASE_URL}/api/staff/${id}/performance`,
  staffRegister: `${BASE_URL}/api/staff/register`,
  staffActivate: (id: string|number) => `${BASE_URL}/api/staff/${id}/activate`,
  staffDeactivate: (id: string|number) => `${BASE_URL}/api/staff/${id}/deactivate`,
  staffGenerateLink: `${BASE_URL}/api/staff/generate-link`,
  // Metro Management endpoints
  metroStations: `${BASE_URL}/api/metro/stations`,
  metroStationById: (id: string|number) => `${BASE_URL}/api/metro/stations/${id}`,
  metroStationActive: `${BASE_URL}/api/metro/stations/active`,
  metroStationDeactivate: (id: string|number) => `${BASE_URL}/api/metro/stations/${id}/deactivate`,
  metroStationUpdate: (id: string|number) => `${BASE_URL}/api/metro/stations/${id}`,
  metroStationDelete: (id: string|number) => `${BASE_URL}/api/metro/stations/${id}`,
  metroStationCreate: `${BASE_URL}/api/metro/stations`,
  metroLinesAll: `${BASE_URL}/api/metro/lines`,
  metroLineById: (id: string|number) => `${BASE_URL}/api/metro/lines/${id}`,
  metroLineActive: `${BASE_URL}/api/metro/lines/active`,
  metroLineDeactivate: (id: string|number) => `${BASE_URL}/api/metro/lines/${id}/deactivate`,
  metroLineUpdate: (id: string|number) => `${BASE_URL}/api/metro/lines/${id}`,
  metroLineDelete: (id: string|number) => `${BASE_URL}/api/metro/lines/${id}`,
  metroLineCreate: `${BASE_URL}/api/metro/lines`,
  // Metro Line Suspension endpoints
  metroSuspensions: `${BASE_URL}/api/v1/metro/suspensions`,
  metroSuspensionById: (suspensionId: string|number) => `${BASE_URL}/api/v1/metro/suspensions/${suspensionId}`,
  metroSuspensionStationAffected: (stationId: string|number) => `${BASE_URL}/api/v1/metro/suspensions/station/${stationId}/is-affected`,
  metroSuspensionByLine: (metroLineId: string|number) => `${BASE_URL}/api/v1/metro/suspensions/metro-line/${metroLineId}`,
  metroSuspensionLineIsSuspended: (metroLineId: string|number) => `${BASE_URL}/api/v1/metro/suspensions/metro-line/${metroLineId}/is-suspended`,
  metroSuspensionLift: (suspensionId: string|number) => `${BASE_URL}/api/v1/metro/suspensions/${suspensionId}/lift`,
  metroSuspensionRetryNotification: (suspensionId: string|number) => `${BASE_URL}/api/v1/metro/suspensions/${suspensionId}/retry-notification`,
  metroSuspensionAcknowledge: `${BASE_URL}/api/v1/metro/suspensions/acknowledge`,
};
